### ISSUE TITLE
no attribute 'AirmonNg'

### ISSUE THREAD

**Issue by robbyatbln** [XayOn/pyrcrack#21]
Traceback (most recent call last):
  File "pycrack.py", line 30, in <module>
    loop.run_until_complete (scan_for_targets())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "pycrack.py", line 14, in scan_for_targets
    airmon = pyrcrack.AirmonNg()
AttributeError: module 'pyrcrack' has no attribute 'AirmonNg'

###########################################################################

import asyncio

import pyrcrack

from rich.console import Console
from rich.prompt import Prompt

async def scan_for_targets():
    """Scan for targets, return json."""
    console = Console()
    console.clear()
    console.show_cursor(False)
    airmon = pyrcrack.AirmonNg()

    interface = Prompt.ask(
        'Select an interface',
        choices=[a['interface'] for a in await airmon.interfaces])

    async with airmon(interface) as mon:
        async with pyrcrack.AirodumpNg() as pdump:
            async for result in pdump(mon.monitor_interface):
                console.clear()
                console.print(result.table)
                await asyncio.sleep(2)

#asyncio.run(scan_for_targets())
loop = asyncio.get_event_loop ()
loop.run_until_complete (scan_for_targets())

can somebody help me please

**Comment by XayOn** [comment]
Hi @robbyatbln, you named your script "pyrcrack", wich is making it try to import AirmonNg from... itself.
Rename it to something like pyrcrack_test.py and it will work.

**Comment by robbyatbln** [comment]
pi@raspberrypi:~ $ sudo python3.6 pycrack_test.py

Traceback (most recent call last):
  File "pycrack_test.py", line 30, in <module>
    loop.run_until_complete (scan_for_targets())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "pycrack_test.py", line 12, in scan_for_targets
    airmon = pyrcrack.AirmonNg()
AttributeError: module 'pyrcrack' has no attribute 'AirmonNg'
pi@raspberrypi:~ $ 




no, sorry that was not the error

**Comment by robbyatbln** [comment]
pi@raspberrypi:~ $ sudo python3.6
Python 3.6.5 (default, Feb 28 2021, 22:14:14) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyrcrack
>>> airmon = pyrcrack.AirmonNg()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyrcrack' has no attribute 'AirmonNg'
>>>

**Comment by robbyatbln** [comment]
thanks for help

**Comment by XayOn** [comment]
@robbyatbln  Find out where are you getting pyrcrack from. It's not from the library, that's almost sure.
Execute the following:
import pyrcrack
print(pyrcrack.__file__)

You'll probably get another pyrcrack.py file or pyrcrack/ directory with an __init__.py that python is using instead of this library.

**Comment by XayOn** [comment]
I'm reopening this until you get it to work :)

**Comment by robbyatbln** [comment]
pi@raspberrypi:~ $ python3.6
Python 3.6.5 (default, Feb 28 2021, 22:14:14) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyrcrack
>>> print(pyrcrack.file)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyrcrack' has no attribute 'file'
>>>

**Comment by robbyatbln** [comment]
thank you

**Comment by robbyatbln** [comment]
pi@raspberrypi:~ $ pip3.6 install pyrcrack
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pyrcrack in /usr/local/lib/python3.6/site-packages (0.1.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.6/site-packages (from pyrcrack) (5.8.0)
pi@raspberrypi:~ $ python3.6
Python 3.6.5 (default, Feb 28 2021, 22:14:14) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyrcrack
>>> 
>>> 
>>> airmon = pyrcrack.AirmonNg()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyrcrack' has no attribute 'AirmonNg'
>>>

**Comment by XayOn** [comment]
@robbyatbln github formatting messed up my comment. It's not file, it's __file__

```import pyrcrack
print(pyrcrack.__file__)
```

Anyway, I've seen your problem. Recent versions of pyrcrack require recent versions of python. 
The latest works only with python3.8 (and the examples and docs are for that), it's specified in the front page as a pretty badge 😃 

I'm not planning on supporting older versions, you should update your python version and install pyrcrack there. Python3.9 is already stable, 3.6 is old already.

**Comment by XayOn** [comment]
Just to clarify, as older versions are uploaded with 3.6 support, your pip is installing the latest one available for python3.6, wich has a really different api and much less features.
