### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by rexdivakar** [XayOn/pyrcrack#23]
## Detailed Description

I ran the sample program given it ended up with Filenot Found error, tried fixing it but not working kindly give me a solution on it

FileNotFoundError: [WinError 2] The system cannot find the file specified

## Your Environment

* Python version used: 3.9
* Operating System: Windows 10 *64

**Comment by XayOn** [comment]
@rexdivakar  You probably don't have aircrack-ng on your PATH. 
I'd rather recommend you use it on a linux distribution, dragons can happen on windows.
