### ISSUE TITLE
aireplay.run results in a ProcessLookupError

### ISSUE THREAD

**Issue by Tank-Missile** [XayOn/pyrcrack#29]
I ran your example code for aireplay_deauth with some modifications to only make it run until the process has ended instead of making it run forever in a while loop. However, something is going on that makes self.proc.kill() in the \_\_aexit\_\_ method inside the ExecutorHelper class cause this execption. Unfortunately asyncio is not an area of python I am familiar with, even after skimming over the documentation. I was able to fix the error by adding a check to make sure the returncode is None before attempting to kill the process. I also noticed aireplay.run fails to finish successfully without a while loop. I'm not sure what's going on there either. Here is the modified example code:

```python
async def attack(network):
    airmon = pyrcrack.AirmonNg()

    async with airmon('wlan0', network.channel) as mon:
        async with pyrcrack.AireplayNg() as aireplay:
            await aireplay.run('wlan0mon', deauth = 10, D = True, a = network.bssid)

            while aireplay.proc.returncode is None:
                await asyncio.sleep(2)

async def deauth():
    airmon = pyrcrack.AirmonNg()

    async with airmon('wlan0') as mon:
        async with pyrcrack.AirodumpNg() as pdump:
            async for networks in pdump(mon.monitor_interface):
                for network in networks:
                    if network.essid == 'test_network':
                        print(network.asdict())
                        await attack(network)
                        return

asyncio.run(deauth())
```

Here is the fix I used:

```python
if self.running:
    self.proc.kill()
```

**Comment by XayOn** [comment]
Hi @Tank-Missile 

I'm hijacking this issue to address a few concerns, but I'd also like to tell you:

- Be careful on using "wlan0mon" and so hardcoded. If you launch it twice and for some reason it could'nt delete the previous monitor interface, airmon will create wlan0mon1 etc.
- Look at rich.console in the examples, it looks quite good :)

Now, to address my own concerns:

- Having to iterate trough interfaces is not ideal. I'd like to be able to select an interface with a regex.
- Also, having to pass monitor interface name in functions isn't ideal either. I'm doing some experimenting with a context variable for that, and I think It's going to stick 😃 
- Not being able to pass an interface object directly as a run parameter seems wrong. The same for the other objects as an AP one etc. I'm trying to convert them to string before execute().
- 217b8447a90036239bafe677cd976e8880e73046 Introduced a bug on some systems. I guess it's actually a corner case.

**Comment by XayOn** [comment]
Hi @Tank-Missile, could you test current develop branch? Your issue should be fixed, thanks!
