### ISSUE TITLE
AirodumpNg dump meta return no value

### ISSUE THREAD

**Issue by 108102** [XayOn/pyrcrack#8]
Testing airodump.py under example folder
Got the return value like is {} and keyerror

**Comment by XayOn** [comment]
@108102 Can you provide more information on this and use a more recent example file?

**Comment by XayOn** [comment]
@108102 I'm reopening this as i've been able to reproduce it.
There's two things:
- It will happen if you launch it without a monitor-mode interface (wlXmon)
- Second, there's a race condition that happens sometimes that causes this too.

That is on previous versions of aircrack-ng, as csv format has changed (and now the format is consistent to scripting :-) ) I'm migrating to it.

**Comment by XayOn** [comment]
I've realized that if airodump-ng process wen't wrong, it wouldn't raise an exception nor anything, just behave as described.

**Comment by XayOn** [comment]
I'm unifying this in #16
